/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sense.full.v1.Request', null, global);
goog.exportSymbol('proto.sense.full.v1.RequestStream', null, global);
goog.exportSymbol('proto.sense.full.v1.Response', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sense.full.v1.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sense.full.v1.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sense.full.v1.Request.displayName = 'proto.sense.full.v1.Request';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sense.full.v1.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.sense.full.v1.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sense.full.v1.Request} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sense.full.v1.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: msg.getData_asB64(),
    apikey: msg.getApikey(),
    format: msg.getFormat(),
    apiVersion: msg.getApiVersion(),
    userAgent: msg.getUserAgent()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sense.full.v1.Request}
 */
proto.sense.full.v1.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sense.full.v1.Request;
  return proto.sense.full.v1.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sense.full.v1.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sense.full.v1.Request}
 */
proto.sense.full.v1.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApikey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormat(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiVersion(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserAgent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.sense.full.v1.Request} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.Request.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sense.full.v1.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.Request.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = this.getApikey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getFormat();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getApiVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getUserAgent();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.sense.full.v1.Request} The clone.
 */
proto.sense.full.v1.Request.prototype.cloneMessage = function() {
  return /** @type {!proto.sense.full.v1.Request} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional bytes data = 1;
 * @return {!(string|Uint8Array)}
 */
proto.sense.full.v1.Request.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/**
 * optional bytes data = 1;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.sense.full.v1.Request.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.sense.full.v1.Request.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value  */
proto.sense.full.v1.Request.prototype.setData = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string apikey = 2;
 * @return {string}
 */
proto.sense.full.v1.Request.prototype.getApikey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.sense.full.v1.Request.prototype.setApikey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string format = 3;
 * @return {string}
 */
proto.sense.full.v1.Request.prototype.getFormat = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.sense.full.v1.Request.prototype.setFormat = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string api_version = 4;
 * @return {string}
 */
proto.sense.full.v1.Request.prototype.getApiVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.sense.full.v1.Request.prototype.setApiVersion = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string user_agent = 5;
 * @return {string}
 */
proto.sense.full.v1.Request.prototype.getUserAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.sense.full.v1.Request.prototype.setUserAgent = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sense.full.v1.RequestStream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sense.full.v1.RequestStream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sense.full.v1.RequestStream.displayName = 'proto.sense.full.v1.RequestStream';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sense.full.v1.RequestStream.prototype.toObject = function(opt_includeInstance) {
  return proto.sense.full.v1.RequestStream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sense.full.v1.RequestStream} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sense.full.v1.RequestStream.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: msg.getData_asB64(),
    apikey: msg.getApikey(),
    dtype: msg.getDtype(),
    sr: msg.getSr(),
    apiVersion: msg.getApiVersion(),
    userAgent: msg.getUserAgent()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sense.full.v1.RequestStream}
 */
proto.sense.full.v1.RequestStream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sense.full.v1.RequestStream;
  return proto.sense.full.v1.RequestStream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sense.full.v1.RequestStream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sense.full.v1.RequestStream}
 */
proto.sense.full.v1.RequestStream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApikey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDtype(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSr(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserAgent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.sense.full.v1.RequestStream} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.RequestStream.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sense.full.v1.RequestStream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.RequestStream.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = this.getApikey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getDtype();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getSr();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = this.getApiVersion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getUserAgent();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.sense.full.v1.RequestStream} The clone.
 */
proto.sense.full.v1.RequestStream.prototype.cloneMessage = function() {
  return /** @type {!proto.sense.full.v1.RequestStream} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional bytes data = 1;
 * @return {!(string|Uint8Array)}
 */
proto.sense.full.v1.RequestStream.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/**
 * optional bytes data = 1;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.sense.full.v1.RequestStream.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.sense.full.v1.RequestStream.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value  */
proto.sense.full.v1.RequestStream.prototype.setData = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string apikey = 2;
 * @return {string}
 */
proto.sense.full.v1.RequestStream.prototype.getApikey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.sense.full.v1.RequestStream.prototype.setApikey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string dtype = 3;
 * @return {string}
 */
proto.sense.full.v1.RequestStream.prototype.getDtype = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.sense.full.v1.RequestStream.prototype.setDtype = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 sr = 4;
 * @return {number}
 */
proto.sense.full.v1.RequestStream.prototype.getSr = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.sense.full.v1.RequestStream.prototype.setSr = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string api_version = 5;
 * @return {string}
 */
proto.sense.full.v1.RequestStream.prototype.getApiVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.sense.full.v1.RequestStream.prototype.setApiVersion = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string user_agent = 6;
 * @return {string}
 */
proto.sense.full.v1.RequestStream.prototype.getUserAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.sense.full.v1.RequestStream.prototype.setUserAgent = function(value) {
  jspb.Message.setField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sense.full.v1.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sense.full.v1.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sense.full.v1.Response.displayName = 'proto.sense.full.v1.Response';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sense.full.v1.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.sense.full.v1.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sense.full.v1.Response} msg The msg instance to transform.
 * @return {!Object}
 */
proto.sense.full.v1.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    outputs: msg.getOutputs()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sense.full.v1.Response}
 */
proto.sense.full.v1.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sense.full.v1.Response;
  return proto.sense.full.v1.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sense.full.v1.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sense.full.v1.Response}
 */
proto.sense.full.v1.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOutputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.sense.full.v1.Response} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.Response.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sense.full.v1.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.sense.full.v1.Response.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getOutputs();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.sense.full.v1.Response} The clone.
 */
proto.sense.full.v1.Response.prototype.cloneMessage = function() {
  return /** @type {!proto.sense.full.v1.Response} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string outputs = 1;
 * @return {string}
 */
proto.sense.full.v1.Response.prototype.getOutputs = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.sense.full.v1.Response.prototype.setOutputs = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.sense.full.v1);
